name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Install additional dependencies
        run: |
          pip install flake8 black 

      - name: Run linters
        run: |
          black --check .

      - name: Build Docker image
        run: docker build -t woz_prediction .


